{u'ActiveEnterTimestamp': 1302081048288787L,
 u'ActiveExitTimestamp': 0L,
 u'ActiveState': u'active',
 u'After': [u'basic.target'],
 u'AllowIsolate': 0,
 u'Before': [u'pppoe.service',
             u'shutdown.target',
             u'multi-user.target',
             u'graphical.target'],
 u'BindTo': [],
 u'BoundBy': [],
 u'CanIsolate': 0,
 u'CanReload': 1,
 u'CanStart': 1,
 u'CanStop': 1,
 u'ConflictedBy': [],
 u'Conflicts': [u'shutdown.target'],
 u'ControlGroup': [u'cpu:/system/apmd.service',
                   u'name=systemd:/system/apmd.service'],
 u'DefaultControlGroup': u'name=systemd:/system/apmd.service',
 u'DefaultDependencies': 1,
 u'Description': u'LSB: Advanced power management (APM) daemon',
 u'Following': u'',
 u'FragmentPath': u'',
 u'Id': u'apmd.service',
 u'InactiveEnterTimestamp': 0L,
 u'InactiveExitTimestamp': 1302081048049944L,
 u'Job': (0L, '/org/freedesktop/systemd1/unit/apmd_2eservice'),
 u'JobTimeoutUSec': 0L,
 u'LoadState': u'loaded',
 u'Names': [u'apmd.service'],
 u'NeedDaemonReload': 0,
 u'OnFailure': [],
 u'RefuseManualStart': 0,
 u'RefuseManualStop': 0,
 u'RequiredBy': [],
 u'RequiredByOverridable': [],
 u'Requires': [u'basic.target'],
 u'RequiresOverridable': [],
 u'Requisite': [],
 u'RequisiteOverridable': [],
 u'StopWhenUnneeded': 0,
 u'SubState': u'exited',
 u'WantedBy': [u'multi-user.target', u'graphical.target'],
 u'Wants': []}